'use strict';
// Rebuilds the exact pre-fix (commit d08bfd6) datatable+query for the 3 fixtures affected by
// the Track 3 remediation pass, part 5 row-duplication fix, to capture honest "before" evidence
// by re-running the ACTUAL old query text against the same live engine, rather than relying on
// a prior conversation transcript.
//
// PREREQUISITE (manual, one-time): this script reads the pre-fix query text from
// ../prefix-baseline/mcp_subscription_authorization_drift.kql, which is NOT regenerated by this
// script itself (it is the thing being tested, not an output). Fetch it first with:
//   git show d08bfd6:detections/kql/mcp_subscription_authorization_drift.kql \
//     > evidence/native-execution/prefix-baseline/mcp_subscription_authorization_drift.kql
const fs = require('fs');
const path = require('path');

const FIELDS = [
  ['timestamp', 'string'], ['event.name', 'string'], ['principal.id_hash', 'string'],
  ['mcp.subscription.id', 'string'], ['mcp.subscription.instance_id', 'string'],
  ['mcp.authz.binding_id', 'string'], ['mcp.subscription.required_scope', 'dynamic'],
  ['mcp.authz.valid_until', 'string'], ['mcp.authz.grant_expiry', 'string'],
  ['security.hash.key_id', 'string'], ['mcp.subscription.notification_type', 'string'],
  ['mcp.authz.change.type', 'string'], ['mcp.authz.change.source', 'string'],
  ['mcp.authz.change.effective_at', 'string'], ['mcp.authz.change.timing_confidence', 'string'],
  ['mcp.authz.change.affected_scope', 'string'], ['mcp.authz.change.affected_binding_ids', 'dynamic'],
  ['mcp.authz.change.removed_scope', 'dynamic'],
];
function kqlStr(v) { if (v === undefined || v === null) return '""'; return '"' + String(v).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'; }
function kqlDynamic(v) { if (v === undefined) return 'dynamic(null)'; return 'dynamic(' + JSON.stringify(v) + ')'; }
function eventToRow(e) { return FIELDS.map(([k, t]) => (t === 'dynamic' ? kqlDynamic(e[k]) : kqlStr(e[k]))).join(', '); }
function buildDatatable(events) {
  const schema = FIELDS.map(([k, t]) => `['${k}']:${t}`).join(', ');
  const rows = events.map((e) => '  ' + eventToRow(e)).join(',\n');
  return `let MCPSecurityAudit = datatable(${schema}) [\n${rows}\n];\n`;
}
function loadJsonl(file) { return fs.readFileSync(file, 'utf8').split('\n').filter((l) => l.trim()).map((l) => JSON.parse(l)); }

const repoRoot = path.resolve(__dirname, '..', '..', '..'); // evidence/native-execution/converters -> repo root
const outDir = path.join(__dirname, '..', 'prefix-baseline');
const oldKqlQuery = fs.readFileSync(path.join(outDir, 'mcp_subscription_authorization_drift.kql'), 'utf8');

const fixtures = [
  ['V11-07', 'v11_close_exactly_at_notification.jsonl'],
  ['V14-04', 'v14_scope_no_overlap.jsonl'],
  ['V14-05', 'v14_scope_exact_string_not_substring.jsonl'],
];

for (const [id, file] of fixtures) {
  const events = loadJsonl(path.join(repoRoot, 'data/validation/track3', file));
  const fullQuery = buildDatatable(events) + '\n' + oldKqlQuery;
  fs.writeFileSync(path.join(outDir, `${id}.prefix.kql`), fullQuery, 'utf8');
  fs.writeFileSync(path.join(outDir, `${id}.prefix.request.json`), JSON.stringify({ db: 'NetDefaultDB', csl: fullQuery }), 'utf8');
  console.log(`Wrote ${id}.prefix.kql (${events.length} events)`);
}
